# Render Blueprint for PetSOS
# This file allows one-click deployment to Render
# Documentation: https://render.com/docs/blueprint-spec

services:
  # Web Service
  - type: web
    name: petsos-app
    runtime: node
    region: singapore  # Change to nearest region: oregon, frankfurt, singapore
    plan: starter  # $19/month - upgrade to standard/pro as needed
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false  # Set manually in Render dashboard
      - key: SESSION_SECRET
        generateValue: true  # Auto-generate secure secret
      - key: REPLIT_DOMAINS
        sync: false  # Set to your Render app URL
      - key: GOOGLE_CLIENT_ID
        sync: false  # Add from Google Console
      - key: GOOGLE_CLIENT_SECRET
        sync: false  # Add from Google Console
      - key: SENTRY_DSN
        sync: false  # Optional
      - key: VITE_SENTRY_DSN
        sync: false  # Optional
      - key: VITE_GA_MEASUREMENT_ID
        sync: false  # Optional
      - key: DEFAULT_COUNTRY
        value: HK
      - key: DEFAULT_COUNTRY_CODE
        value: +852
      - key: DEFAULT_LANGUAGE
        value: zh-HK
