export const DOG_BREEDS = [
  "Labrador Retriever",
  "Golden Retriever",
  "German Shepherd",
  "French Bulldog",
  "Bulldog",
  "Poodle",
  "Beagle",
  "Rottweiler",
  "Yorkshire Terrier",
  "German Shorthaired Pointer",
  "Boxer",
  "Dachshund",
  "Siberian Husky",
  "Great Dane",
  "Doberman Pinscher",
  "Australian Shepherd",
  "Miniature Schnauzer",
  "Cavalier King Charles Spaniel",
  "Shih Tzu",
  "Boston Terrier",
  "Pomeranian",
  "Shetland Sheepdog",
  "Border Collie",
  "Chihuahua",
  "Corgi",
  "Samoyed",
  "Shiba Inu",
  "Mixed Breed"
];

export const CAT_BREEDS = [
  "Persian",
  "British Shorthair",
  "Maine Coon",
  "Ragdoll",
  "Bengal",
  "Abyssinian",
  "Birman",
  "Oriental Shorthair",
  "Sphynx",
  "Devon Rex",
  "Scottish Fold",
  "American Shorthair",
  "Exotic Shorthair",
  "Siamese",
  "Burmese",
  "Russian Blue",
  "Norwegian Forest Cat",
  "Tonkinese",
  "Himalayan",
  "Manx",
  "Munchkin",
  "Domestic Shorthair",
  "Domestic Longhair",
  "Mixed Breed"
];
